version: '3.1'
services:

  database:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    volumes:
      - ./dump:/var/lib/mysql-dump
    ports:
      - 3306:3306


